spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/JAVA_KIOSK?useSSL=false&allowPublicKeyRetrieval=true
    #근데 DB유저 정보가 PureString으로 프로젝트에 포함되면 위험하지않나?
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    #StartUp 시점에 모든 Bean을 등록하지 않는 설정
    #실행속도를 개선할 수 있음 But 어플리케이션의 초기속도가 늦을 수 있음(개발환경에서만 권장)
    lazy-initialization: false
    #JPA
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true